Zen 599 sidebar scroll
simpleviewinc/keg-herkin pull request #42
Opened 2021-06-25 16:06 UTC by subaya710

**Ticket**: [ZEN-599](https://jira.simpleviewtools.com/browse/ZEN-599)

## Context

When there are many items added to the side-out menu , they pass beyond the bottom edge of the screen. We are not able to view or interact with items at the bottom since there is no scroll bar.

## Goal

Provide a scrollbar to the side-out menu as well as appropriate bottom padding so that all items can be accessed.

## Updates

- repos/tap/theme/components/sidebar/sidebar.js
Added properties top, bottom, overflowY, paddingRight and paddingBottom

- repos/example/test/bdd/features
Added feature files so that side-bar menu is populated automatically with multiple items

- repos/example/tests/bdd/steps/index.js
Modification to ensure app launches with the start command. Note : It was failing to launch initially

- repos/tap/components/sidebar/sidebar.js
Change in class name according to existing standards

## Testing

Docker image : https://github.com/simpleviewinc/keg-herkin/pkgs/container/keg-herkin

However , the above docker image does not have test data so it will be easier to test by launching herkin locally

**Setup**

- Pull this PR => keg herkin && keg pr 42
- Navigate to repos/example folder and then start keg herkin => keg herkin start
- Open launched app at http://herkin-zen-599-sidebarscroll.local.keghub.io/
- Escape from the pop up window so you are on the main site

**Test**

- Open the side bar menu and expand all sub sections 
- The items towards the bottom should have disappeared from view
- hover over the sidebar menu and scroll. 
- you should be able to interact with items in the menu, even items that have moved below the bottom page boundary

2021-06-28 19:41 UTC, lancetipton requested changes
Overall looks good, but there are a few issue to resolve.
Along with the other github comments, the UI has a few issues
1. Odd space between the menu and scroll => https://i.imgur.com/9yVfLoG.png
   1. Not a huge deal, but doesn't look very professional
   2. Would be better if it aligned with the edge of the side-menu
2. The Arrow toggle gets cut-off when hovered => https://i.imgur.com/pDQmnGw.png
   1. It looks like the overflow hidden on some parent element is causing this
3. Empty space below the menu => https://i.imgur.com/OKYnNQ6.png
   1. We should make this white, so it looks like the menu takes up the entire height

Let me know if you have any questions. Thanks

2021-07-07 16:20 UTC, subaya710 commented
Changes requested have been made . Adding a new wrapper div and styling it as required solves the 3 issues reported in the review

2021-07-07 17:33 UTC, lancetipton requested changes
I didn't run the code, but there are a few updates that are needed. resubmit the PR after making the updates, and I'll run it then.

Thanks

2021-07-07 17:33 UTC, lancetipton commented on repos/tap/theme/components/sidebar/sidebar.js
> +    position: 'fixed',
Remove the extra space at the end of this line

2021-07-07 17:33 UTC, lancetipton commented on repos/tap/components/sidebar/content/fileTreePanel.js
> +const treeScroll = {overflowY: "scroll", height: "100vh", paddingBottom: "9em" }
This should not be defined inline like this.
Either move it to a theme file, or use `reStyle` from retheme

2021-07-07 17:33 UTC, lancetipton commented on repos/tap/components/sidebar/content/fileTreePanel.js
> +  console.log(styles)
You already mentioned you would remove this, so I'm just putting a comment here for so I remember to check it

2021-07-08 23:10 UTC, lancetipton approved these changes
Excellet work. Looks good, thanks

2021-07-08 23:55 UTC, mpcarolin approved these changes
Looks good. Thanks!

If you can figure out the dynamic `paddingBottom`, that would be an awesome stretch goal, but no worries if not.

2021-08-08 01:11 UTC, merged